Display expiration date consistently.
gdarko/digital-license-manager pull request #6
Opened 2022-08-17 22:54 UTC by pondermatic

* Added a function to `SettingsFieldsTrait` that renders text input fields.
* Added the ability to use a default setting field value.
* Added an `expiration_format` setting to the `dlm_settings_general` option.
  * Defaults to `{{DATE_FORMAT}}, {{TIME_FORMAT}} T`.
  * In the field description, added a link to the WordPress general settings page and a link to the WordPress date and time formatting documentation.
* The `{{DATE_FORMAT}}` and `{{TIME_FORMAT}}` merge codes are replaced with values from `get_option( 'date_format' )` and `get_option( 'time_format' )` respectively.
* Updated the following places to use `wp_date()` and `DateFormatter::getExpirationFormat()`:
  * certificate PDF
  * the bought licenses in the "My Account > Orders" page
  * the license expired error message when activating, deactivating, and reactivating
  * all calls to `DateFormatter::toHtml()`:
    * the "License Manager > Licenses" page
    * the "My Account > Licenses" page
    * the "My Account > Licenses > single" page
  * the licenses template that is added to the "order complete" email
* Updated the "Expires at" description in the "License Manager > Licenses > Add license" and "License Manager > Licenses > Edit license" pages to clarify the time of the day that the license expires.

Fixes #4.

2022-08-18 14:01 UTC, gdarko requested changes
@pondermatic  - Thank you. Looks good to me. Can you move this field in the top "Licenses" section? I think it makes more sense to be there because this is directly related to the Licenses.

Maybe also name "License expiration format" so the users know what it is about.

2022-08-18 14:25 UTC, gdarko approved these changes

2022-08-18 14:25 UTC, gdarko approved these changes

2022-08-18 14:26 UTC, gdarko approved these changes

2022-08-18 14:26 UTC, gdarko approved these changes

2022-08-18 14:27 UTC, gdarko approved these changes

2022-08-18 14:27 UTC, gdarko approved these changes

2022-08-18 14:27 UTC, gdarko approved these changes

2022-08-18 14:28 UTC, gdarko approved these changes

2022-08-18 23:10 UTC, pondermatic commented
> Can you move this field in the top "Licenses" section? I think it makes more sense to be there because this is directly related to the Licenses.

I agree that the "Licenses" is a better place.

> Maybe also name "License expiration format" so the users know what it is about.

OK.

2022-08-19 21:58 UTC, gdarko approved these changes
Thank you! Looks excellent.

2022-08-19 21:58 UTC, merged